env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
    - go mod download
builds:
  - id: "dev-script-runner"
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: dev
    tap:
      owner: sandstorm
      name: homebrew-tap
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de
    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula
    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/dev-script-runner"
    # Your app's description.
    # Default is empty.
    description: "Sandstorm Dev Script Runner"
    # This is a common pattern in Homebrew formulae. We install the directory
    # under bin/, as that directory is supposed to contains executables only,
    # but rather to install both the script and the directory in some place,
    # then create a wrapper in bin/ that calls the script from that place.
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script libexec/"dev"
